---

- name: Install apache2
  apt:
    name: apache2
    state: latest

- name: Stop apache2
  service:
    name: apache2
    state: stopped

- name: Create dirs
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - /var/www/html/images/
    - /var/www/html/images/build/
    - /var/www/html/images/release/

- name: Start apache2
  service:
    name: apache2
    state: started

