---

- name: Create aibuild database
  mysql_db:
    name: aibuild
    state: present
    encoding: utf8
    login_user: root
    login_password: "{{ ansible_ssh_pass }}"

- name: Grant all privileges for aibuild
  command: 'mysql -uroot -p{{ ansible_ssh_pass }} -ne "{{ item }}"'
  with_items:
    - GRANT ALL PRIVILEGES ON aibuild.* TO 'aibuild'@'localhost' IDENTIFIED BY '{{ ansible_ssh_pass }}'
    - GRANT ALL PRIVILEGES ON aibuild.* TO 'aibuild'@'%' IDENTIFIED BY '{{ ansible_ssh_pass }}'

- name: Git clone aibuild src
  git:
    repo: https://github.com/ericxiett/aibuild.git
    dest: /opt

- name: Install pkgs
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pecan
    - apache2
    - mod_wsgi

- name: Install aibuild python libs
  command: python setup.py develop
  args:
    chdir: /opt/aibuild/

- name: Create log dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/log/aibuild
    - /etc/aibuild

- name: Copy aibuild.conf
  template:
    src: aibuild.conf.j2
    dest: /etc/aibuild/aibuild.conf

- name: Sync db
  command: python dbsync.py create
  args:
    chdir: /opt/aibuild/aibuild/cmd/

- name: Copy conf for mod_wsgi
  template:
    src: apache2_aibuild.conf.j2
    dest: /etc/apache2/conf-available/aibuild.conf

- name: Create softlink
  command: ln -s /etc/apache2/conf-available/aibuild.conf /etc/apache2/conf-enabled/aibuild.conf

- name: Start aibuild
  service:
    name: apache2
    enabled: yes
    state: restarted
