---

- name: Install git
  apt:
    name: git
    state: latest

- name: Create aibuild database
  mysql_db:
    name: aibuild
    state: present
    encoding: utf8
    login_user: root
    login_password: "{{ ansible_ssh_pass }}"

- name: Grant all privileges for aibuild
  command: 'mysql -uroot -p{{ ansible_ssh_pass }} -ne "{{ item }}"'
  with_items:
    - GRANT ALL PRIVILEGES ON aibuild.* TO 'aibuild'@'localhost' IDENTIFIED BY '{{ ansible_ssh_pass }}'
    - GRANT ALL PRIVILEGES ON aibuild.* TO 'aibuild'@'%' IDENTIFIED BY '{{ ansible_ssh_pass }}'

- name: Git clone aibuild src
  git:
    repo: https://github.com/ericxiett/aibuild.git
    dest: /opt/aibuild

- name: Install pkgs
  apt:
    name: python-pecan
    state: latest

- name: Install aibuild python libs
  command: python setup.py develop
  args:
    chdir: /opt/aibuild/

- name: Create log dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/log/aibuild
    - /etc/aibuild

- name: Copy aibuild.conf
  template:
    src: aibuild.conf.j2
    dest: /etc/aibuild/aibuild.conf

- name: Sync db
  command: python aibuild_client.py db create
  args:
    chdir: /opt/aibuild/aibuild/cmd/

- name: Copy start script
  copy:
    src: files/start_server.sh
    dest: /opt/aibuild/

- name: Start server
  command: sh start_server.sh
  args:
    chdir: /opt/aibuild/
