---

- name: Get start timestamp
  hosts: deploy
  connection: local
  tasks:
    - set_fact:
        starttime: '{{ ansible_date_time }}'

- name: Setup worker
  hosts: aibuild01
  user: root
  roles:
    - worker

- name: Setup cid env
  hosts: aibuild02
  user: root
  roles:
    - cid

- name: Setup db
  hosts: aibuild01
  user: root
  roles:
    - db

- name: Setup aibuild server
  hosts: aibuild01
  user: root
  roles:
    - server

- name: Inform installer
  hosts: deploy
  connection: local
  tasks:
    debug:
      msg: >-
        The workload started at {{ hostvars.deploy.starttime.time }}
        ended at {{ ansible_date_time.time }}