---

- name: Get start timestamp
  hosts: deploy
  connection: local
  tasks:
    - set_fact:
        starttime: '{{ ansible_date_time }}'

- name: Setup worker
  hosts: worker
  user: root
  roles:
    - worker

- name: Setup cid env
  hosts: aibuild
  user: root
  roles:
    - cid

- name: Setup db
  hosts: aibuild
  user: root
  roles:
    - db

- name: Setup aibuild server
  hosts: aibuild
  user: root
  roles:
    - server

- name: Setup web server for storage and release images
  hosts: worker01
  user: root
  roles:
    - web

- name: Inform installer
  hosts: deploy
  connection: local
  tasks:
    - debug:
        msg: >-
          The workload started at {{ hostvars.deploy.starttime.time }}
          ended at {{ ansible_date_time.time }}