---

- name: Install qemu-kvm and unzip
  apt:
    name: ['qemu-kvm', 'unzip', 'virt-sysprep']
    state: latest

- name: Download packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
    dest: /opt

- name: Unzip packer
  unarchive:
    src: /opt/packer_1.2.5_linux_amd64.zip
    dest: /opt
    remote_src: yes
    mode: ug+x
